### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by zrothauser** [10up/Engineering-Best-Practices#104]
Splitting off the discussions from #101 into separate issues:

Responsive images can be considered in two places: their use in the theme (static images and featured post images, for example), and embedded images inside post content.

One way that I've dealt with images (for the post featured images) can be seen here:
https://gist.github.com/zrothauser/a8e27f68d4ccdfb9881c
which would result in a syntax of: https://gist.github.com/zrothauser/a58d1d3cf4cc3f285a85

One potential core feature (currently in progress) to consider:
https://make.wordpress.org/core/2015/08/25/responsive-image-support-update/

**Comment by devinsays** [comment]
I definitely think we should consider using responsive images any time the theme defines and outputs large featured images.

Browser support listed here: http://caniuse.com/#feat=srcset. IE doesn't yet support srcset, but I don't see any reason why this couldn't just be used as a progressive enhancement for Chrome, Firefox, and Safari users.

I haven't had a chance to do a lot of testing with it yet, but I'll also put together a few examples. Ideally we'll have a fairly simple function that can output appropriate markup.

From my read, the core proposal aims to deal with images in content (at least to start), though that conversation is definitely worth following.

Also, link to the spec in case anyone is curious: http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-img-srcset

**Comment by tddewey** [comment]
**For image markup as part of the theme**, I would like to see us take more advantage of srcset. As @devinsays mentioned, it seems pretty safe to do this across the board.

Some notes:
1. Devs will need to be careful about how many image sizes they're asking WordPress to create. I'd prioritize front-end speed over disk space and back-end performance, but still. It can get ridiculous.
2. The case for a JIT image sizing application (e.g. photon) becomes stronger.
3. I'd like to see some best practices on how to use the spec. (e.g. do we use pixels or ems, when should we be using the "sizes" attribute, etc).

---

There are a lot of moving pieces to consider **for responsive images in-content** — consider all the different alignment options, captions (or not), plus the image editor. I'd suggest we continue to make this project and theme dependent/optional until we are consistently applying srcset as outlined above and have a clear implementation plan. Or until core supports it. Whichever comes first.

**Comment by nicoladj77** [comment]
One thing about srcset is that it might have some drawbacks as I think all images are loaded and not only the image for the used size. I remember @kdo talking about this and [found it also as question](http://stackoverflow.com/questions/26574422/how-do-i-tell-srcset-attribute-to-load-no-images-when-viewport-smaller-than-cert)
It's a good idea to lazyload srcset too. 
In the project I'm working on, TEN, we use javascript to choose the image size at runtime, so that only one image is loaded, which is one solution to the problem but obviously has some edge cases where it doesn't work perfectly.

**Comment by tlovett1** [comment]
@devinsays is right - the core proposal only addresses post inline images. I love the idea of standarizing on `srcset`. However, we have to find a way to solve the problem that meets a pretty diverse set of client needs. It is not the best use of anyone's time to create five versions of every single image. I feel like whatever we do has to include a JIT strategy for this to be feasible since `srcset` loads all images.

**Comment by devinsays** [comment]
I've been working on this, looking at featured images in Twenty Fifteen specifically. I should have something ready to share soon. In many cases, using srcset with multiple image sources could increase page load if retina images are used, which is something to consider.

**Comment by zrothauser** [comment]
I think the increase in page load time is generally worth it on a retina notebook/desktop - the benefit is in the quality here, rather than the load time.

**Comment by devinsays** [comment]
I did a bit of a deep dive into this subject using Twenty Fifteen as an example project:
http://wptheming.com/2015/09/responsive-image-best-practices/

General conclusions:
- We'll likely only start to see performance gains if default images are ~650px+ due to retina screens on many mobile devices.
- Responsive images may not make sense for all sites. It depends on the type of traffic and screen usage.

Implementation Thoughts:

If we decide responsive images do make sense for a project, the RICG Responsive Images plugin does have terrific functions available for generating the srcset and sizes attributes.

I think we should have standards on how to implement responsive images in our projects (since some of us will surely start using this soon).

I'm not sure we'd want to use the plugin RICG as a whole (maybe?), but we could also fork out the functions that generate srcset and size attributes if we want to just use this for images we control (output by template as opposed to content).

**Comment by dana-ross** [comment]
Responsive image support landed in WordPress core three months after the last comment on this issue.

Closing. Core's functionality is working pretty well for us.

I do like @tddewey 's notes about documenting best practices for using responsive images though. Would be neat if someone could pick that up and run with it.
