### ISSUE TITLE
Internationalization by default

### ISSUE THREAD

**Issue by stevegrunwell** [10up/Engineering-Best-Practices#114]
@nicoladj77 brought up an excellent point this morning in a discussion on a current project: is it worth adding a section that advocates using i18n functions by default and never hard-coding a string in a theme?

Example:

``` php
<h1><?php 
  esc_html( 
    sprintf( __( 'Search results for "%s"', 'text-domain' ), get_search_query() ) 
  ); 
?></h1>
```

vs.

``` php
<h1>Search results for "<?php the_search_query(); ?>"</h1>
```

Internationalization by default forces us to think about what content we're hard-coding, makes the sites ready to be translated at a moments' notice and, especially given core's recent (re-)focus on i18n, _feels_ like a strong recommendation. Being translatable [is also a requirement for themes submitted to WordPress.org](https://make.wordpress.org/themes/handbook/review/required/#language), so there's some degree of precedent.

**Comment by lkwdwrd** [comment]
+1

This is something we've discussed before and always decided to punt the conversation because it's not always something that's needed and means more function call overhead, and can potentially add coding time. However, I'm ready to say "yes"  here.

The run time overhead is minimal at best. Whenever I run profiling on projects with i18n, we're talking in the 1s of milliseconds overhead. As far as coding time, it does take a bit to get into the habit of writing i18n ready code, but that's all it is, a habit. Once the habit is developed, an engineer can write i18n ready code just as fast as they could write non-translation ready code previously.

As for not needing it, I think @stevegrunwell is right that this will only become more relevant as time goes on. And for the client who doesn't need it at first and then needs it later, the overhead of doing it when first writing the code vs. auditing and adding it in later is huge. It can take hours to go through and find all the strings requiring translation after the fact.

**Comment by DrewAPicture** [comment]
I agree with @lkwdwrd.

> And for the client who doesn't need it at first and then needs it later, the overhead of doing it when first writing the code vs. auditing and adding it in later is huge. It can take hours to go through and find all the strings requiring translation after the fact.

I think this argument also goes to what @tddewey has written previously in terms of microcopy. If you're localizing strings and generating pot files, this makes you a lot more aware of where and what you're saying in the form of microcopy and in a lot of cases you might be saying the same thing in multiple places with different text. Having an awareness of what you're saying and where can really allow you to more tightly tie that messaging together for a cohesive strategy.

**Comment by nicoladj77** [comment]
@lkwdwrd +1 

that's exactly what I think

**Comment by emeaguiar** [comment]
Probably should be using escaping functions from the start, `esc_html__` instead of `__` and `esc_html_e` instead of `_e`

**Comment by tlovett1** [comment]
I think it's probably time to go ahead with this one. Agree with everything here. Anyone interested in spearheading the PR?

**Comment by DrewAPicture** [comment]
I've started work on a PR in #115.

**Comment by tlovett1** [comment]
@DrewAPicture any sense when this will be finished?

**Comment by tlovett1** [comment]
Anyone want to finish this up?

**Comment by bswatson** [comment]
I'll take it.

**Comment by moraleida** [comment]
This was finished on #190
