### ISSUE TITLE
Composer best practices?

### ISSUE THREAD

**Issue by dana-ross** [10up/Engineering-Best-Practices#12]
I've gotten questions about Composer best practices when we write themes & plugins. My advice is to use a separate composer.json for each plugin/theme. Do we want to codify this as a best practice (vs a single composer.json for each project)?

Also, Chris Marslender found a way to keep Composer downloads out of Beanstalk repos and run Composer during deploys. Might be good to have him document that to keep our repos small.

**Comment by tlovett1** [comment]
@ericmann is doing work that relates to this in a "project structure" section.

**Comment by ericmann** [comment]
@daveross Yes, every project should have a `composer.json` file, even if we're not using Composer on that project to handle its dependencies. This will make it easier for projects down the line to include/reference existing projects when we need them.

For projects we're hosting, we can (and will) use Composer to manage dependencies and `.gitignore` the `/vendor` directory and re-run Composer on the server during deploys. For some projects (i.e. VIP), though, this isn't possible, so we're making Composer management optional (highly recommended) rather than a requirement.
