### ISSUE TITLE
Use colon syntax for PHP loops and conditionals

### ISSUE THREAD

**Issue by ivankruchkoff** [10up/Engineering-Best-Practices#122]
Had a quick peek at a big cross-section of our codebase, and after removing all preceeding whitespace, out of those that begin with for, if, while:
cat loops-conditionals|grep :|wc -l ~= 100
cat loops-conditionals|grep {|wc -l ~= 800

Does it make sense to specify alternate syntax for control structures?

**Comment by emeaguiar** [comment]
I think colon syntax should be preferred when working with markup, and brace syntax when dealing only in code.

So:

```
<div class="posts">
    <?php while ( have_posts() ) : ?>
        <h1><?php the_title(); ?></h1>
    <?php endwhile; ?>
</div>
```

And:

```
<?php
    for ( $i = 1; $i < 10; $i++ ) {
        $result += $i;
    }
    echo $result;
?>
```

**Comment by DrewAPicture** [comment]
I'm not sure it's necessary to further define best-practices in using colon syntax in markup. This is already spelled out in the core coding standards for PHP (which we already assert following) under the [brace style](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style) section.

**Comment by emeaguiar** [comment]
Colon syntax is offered as a "if you want to" in the standards though, if we want to enforce it, it would be good to include at least a paragraph.

**Comment by DrewAPicture** [comment]
> Colon syntax is offered as a "if you want to" in the standards though, if we want to enforce it, it would be good to include at least a paragraph.

Fair enough.

**Comment by lkwdwrd** [comment]
I much prefer to see colon style conditionals and loops in markup. It's far
easier to see what is being closed:

<?php if ( true ) : ?>

<div>
 <ul>
  <li></li>
  <li></li>
 </ul>
</div>

<?php endif; ?>

There is no question that that last line closes an if statement. It's a lot
harder to follow brackets in markup.

<?php } ?> <-- what does this close?

You can put in comments and if you are really careful with indenting make
it fairly clear, but it's just more obvious to me in colon syntax.

**Comment by RachelRVasquez** [comment]
I know this is an old thread, but this topic came up recently for me on another project and wanted to share my thoughts. I was used to braces due to the WP standards before joining 10up, but agree that colons can be easier for readability. From what I'm hearing however, we should stick to braces if we're using PHP in a template without any HTML nested inside - but wondering if we should enforce an either/or approach. I feel like whether HTML is nested in PHP statements or not, having a mixture of braces and colons can feel disorganized in templates. I'm leaning towards sticking to colons in PHP templates always and braces in PHP functionality outside of templates - thoughts?

**Comment by ericmann** [comment]
> I'm leaning towards sticking to colons in PHP templates always and braces in PHP functionality outside of templates - thoughts?

Given the typical "colons in HTML, braces elsewhere" approach can be confusing when dealing with PHP targeted for _templates_ versus for _logic_, I can totally understand your leaning and agree 100%. I think that's a solid approach that removes any sort of ambiguity.

**Comment by tlovett1** [comment]
I'm closing this as we follow the WordPress Coding Standards that already dictates this.
