### ISSUE TITLE
browserlist.config

### ISSUE THREAD

**Issue by Camwyn** [10up/Engineering-Best-Practices#169]
Since we now require a .editorconfig file ( #143 ) , should we also consider a [browserlist](https://github.com/ai/browserslist) file? It would solidify the requirements right in the repo and would ensure we're only adding required extensions. 

Truth be told, we're already _supposed_ to be doing this in our grunt tasks, but it seems this would be an easy set-and-forget early on in the project, and an easy way to reference the information?

**Comment by tlovett1** [comment]
This looks awesome. Would love to hear some more opinions.

**Comment by timwright12** [comment]
@tlovett1 @Camwyn I think this is cool for the instances where you're using more than one front-end tool that requires browser versioning. I don't know that I'd require it as a "best practice", but it could be a nice addition to `wp_make` or a place where we're trying to automate system processes.

As we have conversations like this about adding tools into our workflow we should keep an eye on over-automating, because it can prevent more Jr. engineers from learning a large portion of what the code they output actually does. From a personal/professional development standpoint it can be problematic for a company (and an employee) down the road when a tool changes or disappears. Not to say this is that type of tool, but some food for thought. There's a lot of value in having someone "suffer" through browser testing.

When I'm evaluating the addition of a new tool at a team level I ask myself a few things:

1. Will this tool create an efficiency or just add more overhead?
2. Will it produce better code?
3. Will it create a better engineer?

For **browserlist** IMHO:
1. It creates a single reference point in the instance where you have multiple. For me, personally, I only use `autoprefixer` with browser versions so this would be redundant, but that's not to say it wouldn't create an efficiency for others.
2. Possibly, but really just more targeted to the SOW
3. Probably not

My 2 cents on this would be to evaluate if we have a need for it within `wp_make`, document it, and let the lead FEE on a project decide based on the project needs, if it should be included.

**Comment by jonathantneal** [comment]
I hope you’ll consider adding something about Browsers Lists. It’s useful for autoprefixer, yes, but also for [babel-preset-env](https://github.com/babel/babel-preset-env#support-a-browsers-option-like-autoprefixer), if you’re using any ES6 stuff.

Browsers lists only settle the minutia produced by the tools you already use. I think that means developers can focus more time on practical knowledge. They’ll still encounter/learn the oddities/unsupporteds as they arise.

Personal Note: I think it’s great fun to know that IE and Edge yet support `vmax` and that IE9-11 standardized on `vm` instead of `vmin`. How odd, right? Still, I recognize that it’s probably more *practical* to help devs understand what `vmax` and `vmin` actually do, and to allow a browsers list to work with a plugin like [postcss-vmax](https://github.com/jonathantneal/postcss-vmax) to just fill in the missing support. In this way, using and recommending a browsers list is similar to using or recommending [sanitize.css and normalize.css](https://10up.github.io/Engineering-Best-Practices/css/#resets) rather than training developers to memorize browser idiosyncrasies.

And, to jump on one of the original motivations that they’re *an easy way to reference the information* — yes — browsers lists are a great way to explicitly make known the browser support to any new developer(s) jumping into an existing project.

**Comment by tlovett1** [comment]
Great discussion. I'm fine with waiting the standard out a bit longer to see if it really sticks.
