### ISSUE TITLE
When to use ES6 arrow functions?

### ISSUE THREAD

**Issue by dana-ross** [10up/Engineering-Best-Practices#177]
I'm going to come right out and say it: I love arrow functions. Combine arrow functions with some array filtering & mapping and…wow. Isn't it cool to compress a whole block of code into a one-liner?

Well…no, not always. And I'd like us to add a section on arrow functions to our best practices.

In our collective experience using ES6 so far, what challenges have we faced writing legible arrow functions? Are they worth using at all, or is it enough to put guidelines in place for when they make sense?

**Comment by dana-ross** [comment]
Maybe it's just me (disclaimer: I've been writing JavaScript since it came into being). When passing a function as a parameter (for example, a callback), I like seeing the word "function", with my editor flagging it in a different color so it stands out. At a glance, I can tell there's a function being passed, which can be lost with an arrow function.

**Comment by ivankruchkoff** [comment]
The question can be rewritten as: When to use lambdas, modules, closures, variadic functions etc?

Or in a php equiv: When to use Namespaces, classes, anonymous functions, etc.

I don't think it makes sense to specify how X lang feature should be used as a best practice, because one person's love of a language feature is another person's hate.

I'm in favour of two things: 1) project consistency (don't deviate from the style a project has been using) 2) allowing the engineering team to engineer how they prefer too (design patterns and language features in use).

Perhaps it's worth scenarios where we like using arrow functions, and leaving it at that without calling it a best practice, especially given that IDEs will change to handle syntax highlighting related to newer JS features.

**Comment by goldenapples** [comment]
I think that when arrow functions vs. anonymous functions vs named functions is just a stylistic choice, then it's totally fine to leave that up to to developer preference and project consistency.

The main case where I see arrow functions as useful and worth specifying as a best practice (when you can write ES6) is when functionally they behave differently than anonymous functions, for example if you want to preserve the `this` context of the surrounding block scope. 

For example, I'd say this:

```
setTimeout( 
    () => { 
        /* do something */ 
        console.log( this ); 
    } 
)
```

is much better than this:

```
setTimeout( 
    function(){ 
        /* do something */ 
        console.log( this ); 
    }.bind( this )
)
```

or this:

```
var self = this;

setTimeout( 
    function(){ 
        /* do something */ 
        console.log( self ); 
    }
)
```

**Comment by zanematthew** [comment]
Why not just a community based JavaScript coding standards?

>Why? It creates a version of the function that executes in the context of this, which is usually what you want, and is a more concise syntax.
>
>Why not? If you have a fairly complicated function, you might move that logic out into its own function declaration.

https://github.com/airbnb/javascript#arrow-functions

**Comment by tlovett1** [comment]
I don't think the arrow function vs. closure function in PHP is the same thing at all. Arrow functions are purely stylistic. PHP closures have structural/design pattern consequences IMO.

As for arrow functions, I don't like them. It's harder for me to read. I say "leave it up to the developer".

**Comment by dkoo** [comment]
I really like arrow functions, and in practice I make heavy use of them in exactly the situation highlighted by @goldenapples—when creating a small, anonymous event handler or callback for something like `setTimeout`/`setInterval`. I even prefer the more concise syntax when simply creating non-callback or non-handler functions, so I agree with "leave it up to the developer."

However, maybe it's worth noting what arrow functions are _not_ very good at, i.e. being methods—I've run into [this example situation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Arrow_functions_used_as_methods) and gotten tripped up when `this` ended up being undefined. They're definitely better suited to a more functional style of writing, and this is where I think they truly shine.

**Comment by jonathantneal** [comment]
@dkoo, fwiw, would you agree that scenario looks a lot like the day you realize you’re using an object as a class without just making a class?

**Comment by dkoo** [comment]
@jonathantneal, That's a good point. Maybe it's a situation that only arises while you're transitioning away from ES5.

**Comment by fuhton** [comment]
I'm not sure that arrow functions are purely stylistic. @goldenapples did a great job explaining some of the context implications that arise from the pattern and these functions definitely can change the structural impacts and design patterns of mappings and other chaining commands (.filter, .find, .concat). When taking a functional approach to JavaScript, arrow functions are a really great tool. 

I do think arrow functions should be encouraged, but shouldn't be required since it isn't an immediate switch from `function() {}` to `() => {}`. They aren't the best practice in every circumstance and should be fully understood before being used.

**Comment by dana-ross** [comment]
Great discussion here. I'm going to close the issue without a pull request because I haven't seen this syntax abused to make unreadable code. Thanks everyone!
