### ISSUE TITLE
Best Practice for installing bundler?

### ISSUE THREAD

**Issue by jgraup** [10up/Engineering-Best-Practices#187]
I am trying to add bundler to compile this project but I am getting permission errors. 

``` bash
$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

There is a lot of conflicting information on how to get around this issue.

What do you recommend as the best way to install `bundler` in order to compile this project?

**Comment by ericmann** [comment]
From the looks of your error, you're running with the version of Ruby that comes with MacOS. I've faced the same issue myself, and what I did to resolve the problem was:
- Install [Homebrew](https://brew.sh/)
- Install [Ruby from Homebrew](https://www.ruby-lang.org/en/documentation/installation/#homebrew) (`brew install ruby`)
- Force the Homebrew version of Ruby to be used (`brew link -f ruby`)
- Install Bundler (`gem install bundler`)

The issue you're running into is that the default gem directory is locked to only users admin access. _Sometimes_ running `gem install` under `sudo` will resolve it, but that's not a guarantee with the way Mac has locked down the directory. It's safer in this instance to use the Homebrew version as it's installed in a `/usr/sbin` directory (and still added to your `PATH` if you `link -f` properly), which is user-writeable.

**Comment by jgraup** [comment]
@ericmann - Thank-you! 

This worked following your instructions.

Small caveats:

* After installing and linking, terminal needed to be restarted for the path changes to take affect.
* After terminal restart, I was able to install bundler without the original issue.
* Running `bundle exec jekyll serve` gave an error : `Gem::LoadError: You have already activated json 2.0.2, but your Gemfile requires json 1.8.6. Prepending 'bundle exec' to your command may solve this.`
* Editing the `Gemfile.lock` to use `json 2.0.2` fixed the final issue and allowed the build/server process.
