### ISSUE TITLE
Progressive Enhancement / JavaScript

### ISSUE THREAD

**Issue by jonathantneal** [10up/Engineering-Best-Practices#72]
Would [Markup’s Progressive Enhancement section](https://10up.github.io/Engineering-Best-Practices/markup/#progressive-enhancement) for [Polyfills](https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/_includes/markdown/Markup.md#polyfills) (and perhaps Modernizr as well) be better positioned beneath [JavaScript’s](https://10up.github.io/Engineering-Best-Practices/javascript/) [Only Load Libraries You Need section](https://github.com/10up/Engineering-Best-Practices/blob/gh-pages/_includes/markdown/JavaScript.md#only-load-libraries-you-need)?

**Comment by tlovett1** [comment]
Hmm I see the theory. I still think markup makes the most sense but could definitely be convinced otherwise.

**Comment by zrothauser** [comment]
I think it still makes more sense in the markup section. I would add HTML5/CSS polyfills when I'm actively working on markup/styling. Other libraries would be considered at a different point, when I'm working on writing JavaScript.

But it could be worth mentioning again in the "Libraries" section, since there are JavaScript polyfills that could be needed - so I think a link back to the Polyfills section on the Markup page might be worth adding to this section.

**Comment by dana-ross** [comment]
@tlovett1 No discussion on this in two years. Want to go ahead & close this one?

**Comment by tlovett1** [comment]
Agreed.
